nome = input ('Qual o seu nome? ')
dia = input ('Informe o dia do seu nascimento: ')
mes = input ('Informe o mês do seu nascimento: ')
ano = input ('Informe o ano do seu nascimento: ')
print('Olá,',nome,'! Prazer em te conhecer!')
print ('Você nasceu no dia',dia,'de ',mes, 'de',ano,'.')
